### PR TITLE
[Doc] Update README to talk about the CI process.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/2194)

### CODE REVIEW

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/2194)* status: Missing an assignee or a reviewer, Unresolved discussions

___
*[README.md, line 55 at r1](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-MBDoLQu8njUz1mprLhc:-MK00HkDAmdlL0rwMqXE:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/2526d0842acb46a2fbf94bc6fae9d6459758261e/README.md#L55)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I suggest we spell it here "Continuous integration"
</blockquote></details>

Done.
___
*[README.md, line 57 at r1](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-MBDnYyQ1DjWpdmGUxLA:-MK00LjDDChjc0d7IwNK:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/2526d0842acb46a2fbf94bc6fae9d6459758261e/README.md#L57)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

and if it **succeeds**, run**s** a job in ...
</blockquote></details>

Done.
___
*[README.md, line 70 at r1](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-MBDnny4BYGoWez1JBM1:-MK00UqX76__P9e11m1a:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/2526d0842acb46a2fbf94bc6fae9d6459758261e/README.md#L70)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think this one should go before the other config as you need to get that in master before you can have the dependant repo.
</blockquote></details>

Done.
___
*[README.md, line 76 at r1](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-MBDo-aX3lGtcOQBc8he:-MK00YPXB4qok_7e59s2:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/2526d0842acb46a2fbf94bc6fae9d6459758261e/README.md#L76)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please straighten the curly quotes.

Also give a real life example for the package version
</blockquote></details>

Done.
___
*[README.md, line 76 at r1](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-MBDoCm8Aq34PMiuNixn:-MK00nXs9gRH7kqX4DlJ:b24mwaf) ([raw file](https://github.com/bayesimpact/docker-react/blob/2526d0842acb46a2fbf94bc6fae9d6459758261e/README.md#L76)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please also document the use of OVERRIDDEN_PACKAGE in a § below.
</blockquote></details>

Moot. It's been dropped

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/2194)* status: Missing an assignee or a reviewer

*[a discussion](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-MBDoPTZ2Z7xKOfoerlt:-MK0VDJW54Rv8S6KAx2U:b-896fix) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Let's not duplicate that doc and keep it only here: once we have resolved the comments in the Google Doc, just drop the entire section and link it to the README or vice versa.
</blockquote></details>

Done.

---

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-:-MK3vWXS8nBhS9DqT7gO:bnfp4nl)* status: Unresolved discussions (README.md:r2 line 57)

___
*[README.md, line 57 at r2](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-MK3vM3015a9Ki9F9pVa:-MK3vM3015a9Ki9F9pVb:b-g5ajp0) ([raw file](https://github.com/bayesimpact/docker-react/blob/0d689b4a522b1170b00759eb17131be41712cd74/README.md#L57)):*
> ```Markdown
> ## Continuous integration
> 
> When running the CI on a branch, CircleCI builds the docker image, and if it succeds, runs a job in the dependant repos. To add a new repo, do the following:
> ```

Is that still true, or is it only for master?

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/2194)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[README.md, line 57 at r2](https://reviewable.io/reviews/bayesimpact/docker-react/2194#-MK3vM3015a9Ki9F9pVa:-MK42IRk3tklPFmJ4C0W:b3tthae) ([raw file](https://github.com/bayesimpact/docker-react/blob/0d689b4a522b1170b00759eb17131be41712cd74/README.md#L57)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Is that still true, or is it only for master?
</blockquote></details>

In this CL, it's still true

**Pull request merged**
