### PR TITLE
Embed a basic webpack config so that setup is slightly faster.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/35)

### CODE REVIEW

**Comment by dedan** [comment]
I really like that idea and I already look forward to using this with new web applications. Currently there was always lots of duplicate work to be done. 

I think we should update the documentation of this repo (the README) as it slightly changed it's purpose now. Currently we describe it simply as a base with some packages installed, so that `npm install` is going to be faster if you base your image on it. I think now we should explain the following points. I will add them as separate comments so that they are easier to be discussed.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7oegtpMomchIC-xjA:-Kf7oegtpMomchIC-xjB:bxvndz3) (no related file):*
The different environments (test, dev, dist).

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7ogghAxdVVD_mIEr_:-Kf7oggiIJNiXw26UT10:b-r8wb61) (no related file):*
What the user would have to do when they want to modify one of the configuration files. Hmm, actually: how would that be done. I like that we would now have an image that provides the functionality to directly run an application with webpack. But if I want to modify lets say the `dev.js` in my project that is based on this image, would I then have to add a copy of the file to my repo and modify it? Would that be a bit confusing to have, in the repo that is based on the image, only a `dev.js` file, but the others (like `dist.js`) are taken from `docker-react`

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7oie8Xtx8lLUmhSoN:-Kf7oie8Xtx8lLUmhSoO:brsx6lx) (no related file):*
Maybe something about how we bind the server to 0.0.0.0 and make it publicly available. 

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7pxEf7yYjLwJtbN-u:-Kf7pxEf7yYjLwJtbN-v:blkmuef) (no related file):*
What are the assumptions that we make on the web application that is compatible with this webpack setup?
* Which is the entrypoint file from which it will include other modules.
* Where is the `index.html` file for it located and how is the javascript included?

---

*[server.js, line 15 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7oue_ONiV-71TprT2:-Kf7oue_ONiV-71TprT3:b-umejop) ([raw file](https://github.com/bayesimpact/docker-react/blob/25f506e08a1c5cd5c228d1dceed73cdc9e038c0d/server.js#L15)):*
> ```JavaScript
>   }
>   console.log('Listening at ' + host + ':' + config.devServer.port)
>   console.log('Opening your system browser...')
> ```

I think we should remove those two lines, because the system browser can't actually be opened from within the docker container, right?

---

*[cfg/dev.js, line 14 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7pXL0KiLrImfJ7fxt:-Kf7pXL0KiLrImfJ7fxu:bup7j5t) ([raw file](https://github.com/bayesimpact/docker-react/blob/25f506e08a1c5cd5c228d1dceed73cdc9e038c0d/cfg/dev.js#L14)):*
> ```JavaScript
>     'webpack-dev-server/client?http://0.0.0.0:0',
>     'webpack/hot/only-dev-server',
>     './src/components/pages/main',
> ```

This entrypoint (in the `pages`) subfolder is very specific. Can you please change it so something like `components/index` and, more importantly, document this in the README?

---

*[cfg/dist.js, line 12 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7pN-DbneQA7cmCRP4:-Kf7pN-DbneQA7cmCRP5:b-aq11rl) ([raw file](https://github.com/bayesimpact/docker-react/blob/25f506e08a1c5cd5c228d1dceed73cdc9e038c0d/cfg/dist.js#L12)):*
> ```JavaScript
>   devtool: 'sourcemap',
>   entry: [
>     // TODO(stephan): Move it somehow to base to make it available in dev as well.
> ```

Can you please un assign me from this TODO?

---

*[cfg/dist.js, line 14 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7pkFKbzwJgTTu-b0P:-Kf7pkFKbzwJgTTu-b0Q:b-2zw83c) ([raw file](https://github.com/bayesimpact/docker-react/blob/25f506e08a1c5cd5c228d1dceed73cdc9e038c0d/cfg/dist.js#L14)):*
> ```JavaScript
>     // TODO(stephan): Move it somehow to base to make it available in dev as well.
>     'babel-polyfill',
>     path.join(__dirname, '../src/components/pages/main'),
> ```

Same as above. Maybe move it to `base.js` to avoid the duplication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-:-Kf7mqta77Ph3-ceewTv:bzb1xmy)*

**Comment by pcorpet** [comment]
Done. Thanks for pushing for that.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7oegtpMomchIC-xjA:-KfHRO7cPIwqiGGW8mEz:b-896fix) (no related file):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

The different environments (test, dev, dist).
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7ogghAxdVVD_mIEr_:-KfHRs619188EBbvmy5E:b-z4fx6s) (no related file):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

What the user would have to do when they want to modify one of the configuration files. Hmm, actually: how would that be done. I like that we would now have an image that provides the functionality to directly run an application with webpack. But if I want to modify lets say the `dev.js` in my project that is based on this image, would I then have to add a copy of the file to my repo and modify it? Would that be a bit confusing to have, in the repo that is based on the image, only a `dev.js` file, but the others (like `dist.js`) are taken from `docker-react`
</blockquote></details>

I don't think it's weird, and in future PR I might simplify what users need to overwrite.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7oie8Xtx8lLUmhSoN:-KfHSRGgcc5I2rQOBlBw:b-896fix) (no related file):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

Maybe something about how we bind the server to 0.0.0.0 and make it publicly available. 
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7pxEf7yYjLwJtbN-u:-KfHVToBD4QePbst4Sjt:b-76ef05) (no related file):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

What are the assumptions that we make on the web application that is compatible with this webpack setup?
* Which is the entrypoint file from which it will include other modules.
* Where is the `index.html` file for it located and how is the javascript included?
</blockquote></details>

Done.
BTW, no need of any index.html.

---

*[server.js, line 15 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7oue_ONiV-71TprT2:-KfHSi-xvprdQ8bSlfxH:b32v57) ([raw file](https://github.com/bayesimpact/docker-react/blob/25f506e08a1c5cd5c228d1dceed73cdc9e038c0d/server.js#L15)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

I think we should remove those two lines, because the system browser can't actually be opened from within the docker container, right?
</blockquote></details>

+1

---

*[cfg/dev.js, line 14 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7pXL0KiLrImfJ7fxt:-KfHUHUSE0ffFlZp1tbY:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/25f506e08a1c5cd5c228d1dceed73cdc9e038c0d/cfg/dev.js#L14)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

This entrypoint (in the `pages`) subfolder is very specific. Can you please change it so something like `components/index` and, more importantly, document this in the README?
</blockquote></details>

Done.

---

*[cfg/dist.js, line 12 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7pN-DbneQA7cmCRP4:-KfHUeigZ2fwnNqLMwSQ:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/25f506e08a1c5cd5c228d1dceed73cdc9e038c0d/cfg/dist.js#L12)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

Can you please un assign me from this TODO?
</blockquote></details>

Done.

---

*[cfg/dist.js, line 14 at r1](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-Kf7pkFKbzwJgTTu-b0P:-KfHUeLquC-4NrUR5lZD:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/25f506e08a1c5cd5c228d1dceed73cdc9e038c0d/cfg/dist.js#L14)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

Same as above. Maybe move it to `base.js` to avoid the duplication.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-:-KfHV29QeErg1Rs2COQK:b-xp62wt)*

**Comment by dedan** [comment]
:lgtm: Thanks for all the changes, the documentation is great!

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 23 at r2](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-KfHdTc8OnEqdga81y88:-KfHdTc8OnEqdga81y89:b-8igeo2) ([raw file](https://github.com/bayesimpact/docker-react/blob/324af8cbbd4594c1a76449838419087433b0b45c/README.md#L23)):*
> ```Markdown
> * **test**, an environment to run automated tests.
> 
> Do not use this image for production, you should compile your React anyway and only push the result of dist.
> ```

Maybe better write "the result of the 'dist' folder", to make clear that you are not speaking about the environment here.

---

*[README.md, line 35 at r2](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-KfHdNxjOdocnVE5Tu18:-KfHdNxjOdocnVE5Tu19:b-8iwhc9) ([raw file](https://github.com/bayesimpact/docker-react/blob/324af8cbbd4594c1a76449838419087433b0b45c/README.md#L35)):*
> ```Markdown
> ## Setup and configuration
> 
> Use it as a base and mount or copy your actual application in `/usr/app`.
> ```

copy TO (i think)

---

*[README.md, line 43 at r2](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-KfHdgQ58A7y0tXGKACY:-KfHdgQ6zWaFD7V-5nWv:b2d61sr) ([raw file](https://github.com/bayesimpact/docker-react/blob/324af8cbbd4594c1a76449838419087433b0b45c/README.md#L43)):*
> ```Markdown
> The actual source of the app should be mounted in `/usr/app/src`, more
> specifically the webpack entrypoint for the app is taken by default from
> `/usr/app/src/components/index`.
> ```

Can you add something about the suffix of this ../components/index? Just from reading the documentation I would not know if I should create a suffix less file or whether it should be index.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-:-KfHeF8os16hE-b3cvrO:bzfku3v)*

**Comment by pcorpet** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[README.md, line 23 at r2](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-KfHdTc8OnEqdga81y88:-KfIBa-E0dZlD66QBgH8:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/324af8cbbd4594c1a76449838419087433b0b45c/README.md#L23)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

Maybe better write "the result of the 'dist' folder", to make clear that you are not speaking about the environment here.
</blockquote></details>

Done.

---

*[README.md, line 35 at r2](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-KfHdNxjOdocnVE5Tu18:-KfIBcq4LCbmFaPOoejE:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/324af8cbbd4594c1a76449838419087433b0b45c/README.md#L35)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

copy TO (i think)
</blockquote></details>

Done.

---

*[README.md, line 43 at r2](https://reviewable.io:443/reviews/bayesimpact/docker-react/35#-KfHdgQ58A7y0tXGKACY:-KfIBh2In_aKARE1nqof:b-896fix) ([raw file](https://github.com/bayesimpact/docker-react/blob/324af8cbbd4594c1a76449838419087433b0b45c/README.md#L43)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

Can you add something about the suffix of this ../components/index? Just from reading the documentation I would not know if I should create a suffix less file or whether it should be index.js
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/35)*

**Comment by dedan** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/35)*

**Pull request merged**
