### PR TITLE
Revert "Bump @types/node from 14.14.34 to 14.14.35"

### PR DESCRIPTION
**Pull request by mlendale**
Reverts bayesimpact/docker-react#3019

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/3022)

### CODE REVIEW

**Review by mlendale — COMMENTED** [review]
+@mlendale 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/3022#-:-MVuTuQF51SVCjkPfPVT:br8kg4o)* status: LGTM missing from one of: emilieguth,pcorpet,zozoens31

**Review by mlendale — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/3022#-:-MVuTxpEBDOr1xd0TybJ:bnfp4nl)* status: LGTM missing from one of: emilieguth,pcorpet,zozoens31

**Review by pcorpet — COMMENTED** [review]
Please explain why somewhere, maybe a link to a failure or even a slack discussion.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/3022#-:-MVv7oDZ3zCN6bYzBxH1:bmrzr16)* status: :shipit: complete! 0 of 1 files reviewed, all discussions resolved

**Comment by mlendale** [comment]
No need to revert.

**Pull request closed without merging**
