### PR TITLE
Fix npm updates in derived Docker due to https://github.com/npm/npm/issues/9863 . Also optimizes Docker layers.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/docker-react/2) &emsp; Multiple assignees:&emsp;@dedan&nbsp;<a href="/bayesimpact/docker-react/pulls/assigned/dedan">dedan</a>,&emsp;@florianjourda&nbsp;<a href="/bayesimpact/docker-react/pulls/assigned/florianjourda">florianjourda</a>

### CODE REVIEW

**Comment by pcorpet** [comment]
+@dedan +@florianjourda 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/2#-:-KGlG52rg1IGNRhWW42s:793040211)*

**Comment by pcorpet** [comment]
Add correct link for issue: https://github.com/npm/npm/issues/9863

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/2#-:-KGlGBt682t27Jrb3B8Z:-683648901)*

**Comment by florianjourda** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 12 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/docker-react/2#-KGlIjwWa_2CNKo4rhGT:-KGlIjwWa_2CNKo4rhGU:1637114088) ([raw file](https://github.com/bayesimpact/docker-react/blob/fe39f33c2dbaf9ef009e54eaf859282c7147da9d/Dockerfile#L12)):*
fun! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/2#-:-KGlImFqJuoxW-nqDAjK:1417088721)*

**Comment by florianjourda** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Dockerfile, line 9 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/docker-react/2#-KGlIqK_nTbmkn4XtOXC:-KGlIqK_nTbmkn4XtOXD:-1837173785) ([raw file](https://github.com/bayesimpact/docker-react/blob/fe39f33c2dbaf9ef009e54eaf859282c7147da9d/Dockerfile#L9)):*
add link to issue to give more context?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/2)*

**Comment by pcorpet** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Dockerfile, line 9 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/docker-react/2#-KGlIqK_nTbmkn4XtOXC:-KGlJVXgpnm1FTxS8DiE:-499146009) ([raw file](https://github.com/bayesimpact/docker-react/blob/fe39f33c2dbaf9ef009e54eaf859282c7147da9d/Dockerfile#L9)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/docker-react/2)*

**Pull request merged**
